/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import java.awt.event.ItemEvent;
import javax.swing.JPanel;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.File;
import java.io.IOException;
import java.time.LocalDate;
import java.time.Year;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.Calendar;
import static java.util.Calendar.MONTH;  

/**
 *
 * @author Elena
 */
public class CalendarMain extends javax.swing.JFrame {

    String monthLabel = "";
    String yearLabel = "";
    int panelSelected = 0;
    Calendar cal = Calendar.getInstance();
    
    /** Creates new form CalendarMain */
    public CalendarMain() {
        /*try {
            calendaryHands = Font.createFont(Font.TRUETYPE_FONT, new File("C:\\FIS Project\\CalendarApp\\src\\main\\resources\\Love.ttf")).deriveFont(18f);
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(calendaryHands);
        } catch (IOException | FontFormatException e){}*/
        initComponents();
        int year = LocalDate.now().getYear();
        int month = LocalDate.now().getMonthValue();
        int date = LocalDate.now().getDayOfMonth();;
        CalendarFiller.year = year;
        CalendarFiller.month = month;
        CalendarFiller.date = date;
        jYearTextField.setText(String.valueOf(year));
        jMonthTextField.setText(String.valueOf(month));
        jDateText.setText(String.valueOf(date));
        jMonthYearLabel.setText("");
}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewMenueGroup = new javax.swing.ButtonGroup();
        jLayeredPanel = new javax.swing.JLayeredPane();
        jYearPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableJan = new javax.swing.JTable();
        label1 = new java.awt.Label();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableFeb = new javax.swing.JTable();
        label2 = new java.awt.Label();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableMar = new javax.swing.JTable();
        label3 = new java.awt.Label();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableApr = new javax.swing.JTable();
        label4 = new java.awt.Label();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableMay = new javax.swing.JTable();
        label5 = new java.awt.Label();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTableJun = new javax.swing.JTable();
        label6 = new java.awt.Label();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTableJul = new javax.swing.JTable();
        label7 = new java.awt.Label();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTableAug = new javax.swing.JTable();
        label8 = new java.awt.Label();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTableSep = new javax.swing.JTable();
        label9 = new java.awt.Label();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTableOct = new javax.swing.JTable();
        label10 = new java.awt.Label();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTableNov = new javax.swing.JTable();
        label11 = new java.awt.Label();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTableDec = new javax.swing.JTable();
        label12 = new java.awt.Label();
        jMonthPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jMonthTable = new javax.swing.JTable();
        jWeekPanel = new javax.swing.JPanel();
        jScrollPane15 = new javax.swing.JScrollPane();
        jWeekTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        DateJumpButton = new javax.swing.JButton();
        jDateText = new javax.swing.JTextField();
        jMonthTextField = new javax.swing.JTextField();
        jYearTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEventList = new javax.swing.JList<>();
        jButtonNext = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jMonthYearLabel = new java.awt.Label();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemYearView = new javax.swing.JRadioButtonMenuItem();
        jMenuItemMonthView = new javax.swing.JRadioButtonMenuItem();
        jMenuItemWeekView = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLayeredPanel.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPanel.setLayout(new java.awt.CardLayout());

        jScrollPane3.setFont(new java.awt.Font("Gill Sans Nova", 1, 8)); // NOI18N

        jTableJan.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTableJan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableJan.setColumnSelectionAllowed(true);
        jTableJan.setRowHeight(11);
        jScrollPane3.setViewportView(jTableJan);
        jTableJan.getAccessibleContext().setAccessibleName("jTableJan");

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label1.setText("January");

        jScrollPane4.setFont(new java.awt.Font("Gill Sans Nova", 1, 8)); // NOI18N

        jTableFeb.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTableFeb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableFeb.setColumnSelectionAllowed(true);
        jTableFeb.setMaximumSize(new java.awt.Dimension(145, 44));
        jTableFeb.setRowHeight(11);
        jScrollPane4.setViewportView(jTableFeb);
        jTableFeb.getAccessibleContext().setAccessibleName("jTableFeb");

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label2.setText("February");

        jScrollPane5.setFont(new java.awt.Font("Gill Sans Nova", 1, 8)); // NOI18N

        jTableMar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTableMar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableMar.setColumnSelectionAllowed(true);
        jTableMar.setRowHeight(11);
        jScrollPane5.setViewportView(jTableMar);
        jTableMar.getAccessibleContext().setAccessibleName("jTableMar");

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label3.setText("March");

        jScrollPane6.setFont(new java.awt.Font("Gill Sans Nova", 1, 8)); // NOI18N

        jTableApr.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTableApr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableApr.setColumnSelectionAllowed(true);
        jTableApr.setRowHeight(11);
        jScrollPane6.setViewportView(jTableApr);
        jTableApr.getAccessibleContext().setAccessibleName("jTableApr");

        label4.setAlignment(java.awt.Label.CENTER);
        label4.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label4.setText("April");

        jScrollPane7.setFont(new java.awt.Font("Gill Sans Nova", 1, 8)); // NOI18N

        jTableMay.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTableMay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableMay.setColumnSelectionAllowed(true);
        jTableMay.setRowHeight(11);
        jScrollPane7.setViewportView(jTableMay);
        jTableMay.getAccessibleContext().setAccessibleName("jTableMay");

        label5.setAlignment(java.awt.Label.CENTER);
        label5.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label5.setText("May");

        jScrollPane8.setFont(new java.awt.Font("Gill Sans Nova", 1, 8)); // NOI18N
        jScrollPane8.setMaximumSize(new java.awt.Dimension(150, 150));

        jTableJun.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTableJun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableJun.setColumnSelectionAllowed(true);
        jTableJun.setRowHeight(11);
        jScrollPane8.setViewportView(jTableJun);
        jTableJun.getAccessibleContext().setAccessibleName("jTableJun");

        label6.setAlignment(java.awt.Label.CENTER);
        label6.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label6.setText("June");

        jScrollPane9.setFont(new java.awt.Font("Gill Sans Nova", 1, 8)); // NOI18N

        jTableJul.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTableJul.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableJul.setColumnSelectionAllowed(true);
        jTableJul.setRowHeight(11);
        jScrollPane9.setViewportView(jTableJul);
        jTableJul.getAccessibleContext().setAccessibleName("jTableJul");

        label7.setAlignment(java.awt.Label.CENTER);
        label7.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label7.setText("July");

        jScrollPane10.setFont(new java.awt.Font("Gill Sans Nova", 1, 8)); // NOI18N

        jTableAug.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTableAug.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableAug.setColumnSelectionAllowed(true);
        jTableAug.setRowHeight(11);
        jScrollPane10.setViewportView(jTableAug);
        jTableAug.getAccessibleContext().setAccessibleName("jTableAug");

        label8.setAlignment(java.awt.Label.CENTER);
        label8.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label8.setText("August");

        jScrollPane11.setFont(new java.awt.Font("Gill Sans Nova", 1, 8)); // NOI18N

        jTableSep.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTableSep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableSep.setColumnSelectionAllowed(true);
        jTableSep.setRowHeight(11);
        jScrollPane11.setViewportView(jTableSep);
        jTableSep.getAccessibleContext().setAccessibleName("jTableSep");

        label9.setAlignment(java.awt.Label.CENTER);
        label9.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label9.setText("September");

        jScrollPane12.setFont(new java.awt.Font("Gill Sans Nova", 1, 8)); // NOI18N

        jTableOct.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTableOct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableOct.setColumnSelectionAllowed(true);
        jTableOct.setRowHeight(11);
        jScrollPane12.setViewportView(jTableOct);
        jTableOct.getAccessibleContext().setAccessibleName("jTableOct");

        label10.setAlignment(java.awt.Label.CENTER);
        label10.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label10.setText("October");

        jScrollPane13.setFont(new java.awt.Font("Gill Sans Nova", 1, 8)); // NOI18N

        jTableNov.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTableNov.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableNov.setColumnSelectionAllowed(true);
        jTableNov.setRowHeight(11);
        jScrollPane13.setViewportView(jTableNov);
        jTableNov.getAccessibleContext().setAccessibleName("jTableNov");

        label11.setAlignment(java.awt.Label.CENTER);
        label11.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label11.setText("November");

        jScrollPane14.setFont(new java.awt.Font("Gill Sans Nova", 1, 8)); // NOI18N

        jTableDec.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTableDec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableDec.setColumnSelectionAllowed(true);
        jTableDec.setRowHeight(11);
        jScrollPane14.setViewportView(jTableDec);
        jTableDec.getAccessibleContext().setAccessibleName("jTableDec");

        label12.setAlignment(java.awt.Label.CENTER);
        label12.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        label12.setText("December");

        javax.swing.GroupLayout jYearPanelLayout = new javax.swing.GroupLayout(jYearPanel);
        jYearPanel.setLayout(jYearPanelLayout);
        jYearPanelLayout.setHorizontalGroup(
            jYearPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jYearPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jYearPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(label1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(label9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jYearPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(label6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(label2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jYearPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(label7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(label11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jYearPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jYearPanelLayout.createSequentialGroup()
                        .addGroup(jYearPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane14, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jYearPanelLayout.setVerticalGroup(
            jYearPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jYearPanelLayout.createSequentialGroup()
                .addGroup(jYearPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jYearPanelLayout.createSequentialGroup()
                        .addGroup(jYearPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jYearPanelLayout.createSequentialGroup()
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jYearPanelLayout.createSequentialGroup()
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jYearPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jYearPanelLayout.createSequentialGroup()
                                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jYearPanelLayout.createSequentialGroup()
                                .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jYearPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jYearPanelLayout.createSequentialGroup()
                                .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jYearPanelLayout.createSequentialGroup()
                                .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jYearPanelLayout.createSequentialGroup()
                        .addGroup(jYearPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jYearPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jYearPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jYearPanelLayout.createSequentialGroup()
                                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jYearPanelLayout.createSequentialGroup()
                                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLayeredPanel.add(jYearPanel, "card2");
        jYearPanel.getAccessibleContext().setAccessibleName("jYearPanel");

        jScrollPane2.setBorder(null);

        jMonthTable.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jMonthTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jMonthTable.setCellSelectionEnabled(true);
        jMonthTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMonthTable.setRowHeight(56);
        jScrollPane2.setViewportView(jMonthTable);
        jMonthTable.getAccessibleContext().setAccessibleName("jMonthTable");

        javax.swing.GroupLayout jMonthPanelLayout = new javax.swing.GroupLayout(jMonthPanel);
        jMonthPanel.setLayout(jMonthPanelLayout);
        jMonthPanelLayout.setHorizontalGroup(
            jMonthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMonthPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                .addContainerGap())
        );
        jMonthPanelLayout.setVerticalGroup(
            jMonthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
        );

        jLayeredPanel.add(jMonthPanel, "card4");
        jMonthPanel.getAccessibleContext().setAccessibleName("jMonthPanel");
        jMonthPanel.getAccessibleContext().setAccessibleParent(jLayeredPanel);

        jWeekTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane15.setViewportView(jWeekTable);
        jWeekTable.getAccessibleContext().setAccessibleName("jWeekTable");

        javax.swing.GroupLayout jWeekPanelLayout = new javax.swing.GroupLayout(jWeekPanel);
        jWeekPanel.setLayout(jWeekPanelLayout);
        jWeekPanelLayout.setHorizontalGroup(
            jWeekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane15, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
        );
        jWeekPanelLayout.setVerticalGroup(
            jWeekPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jWeekPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLayeredPanel.add(jWeekPanel, "card3");
        jWeekPanel.getAccessibleContext().setAccessibleName("jWeekPanel");

        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createTitledBorder(null, "Select Date", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 0, 13)))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N

        DateJumpButton.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        DateJumpButton.setText("Jump");
        DateJumpButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 204), new java.awt.Color(153, 255, 255), null, null));
        DateJumpButton.setBorderPainted(false);
        DateJumpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateJumpButtonActionPerformed(evt);
            }
        });

        jDateText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jDateText.setText("01");

        jMonthTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jMonthTextField.setText("01");

        jYearTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jYearTextField.setText("2021");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DateJumpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jMonthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMonthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DateJumpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        DateJumpButton.getAccessibleContext().setAccessibleName("DateJumpButton");
        jDateText.getAccessibleContext().setAccessibleName("jDateText");
        jMonthTextField.getAccessibleContext().setAccessibleName("jMonthTextField");
        jYearTextField.getAccessibleContext().setAccessibleName("jYearTextField");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Events", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 0, 13)), null)); // NOI18N

        jEventList.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        jEventList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jEventList);
        jEventList.getAccessibleContext().setAccessibleName("jEventList");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jButtonNext.setIcon(new javax.swing.ImageIcon("C:\\Users\\Elena\\Documents\\GitHub\\ProiectFIS\\agenda_electronica\\src\\main\\resources\\next_small.png")); // NOI18N
        jButtonNext.setBorderPainted(false);
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jButtonBack.setIcon(new javax.swing.ImageIcon("C:\\Users\\Elena\\Documents\\GitHub\\ProiectFIS\\agenda_electronica\\src\\main\\resources\\back_small.png")); // NOI18N
        jButtonBack.setBorderPainted(false);
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jMonthYearLabel.setAlignment(java.awt.Label.CENTER);
        jMonthYearLabel.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jMonthYearLabel.setText("Month,Year");

        jMenu1.setText("View");

        viewMenueGroup.add(jMenuItemYearView);
        jMenuItemYearView.setSelected(true);
        jMenuItemYearView.setText("Year");
        jMenuItemYearView.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jMenuItemYearViewItemStateChanged(evt);
            }
        });
        jMenu1.add(jMenuItemYearView);
        jMenuItemYearView.getAccessibleContext().setAccessibleName("jMenuItemYearView");

        viewMenueGroup.add(jMenuItemMonthView);
        jMenuItemMonthView.setText("Month");
        jMenuItemMonthView.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jMenuItemMonthViewItemStateChanged(evt);
            }
        });
        jMenu1.add(jMenuItemMonthView);
        jMenuItemMonthView.getAccessibleContext().setAccessibleName("jMenuItemMonthView");

        viewMenueGroup.add(jMenuItemWeekView);
        jMenuItemWeekView.setText("Week");
        jMenuItemWeekView.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jMenuItemWeekViewItemStateChanged(evt);
            }
        });
        jMenu1.add(jMenuItemWeekView);
        jMenuItemWeekView.getAccessibleContext().setAccessibleName("jMenuItemWeekView");

        jMenuBar1.add(jMenu1);
        jMenu1.getAccessibleContext().setAccessibleName("jMenu");

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jMonthYearLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNext)
                    .addComponent(jButtonBack)
                    .addComponent(jMonthYearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLayeredPanel.getAccessibleContext().setAccessibleName("jLayeredPanel");
        jButtonNext.getAccessibleContext().setAccessibleName("jButtonNext");
        jButtonBack.getAccessibleContext().setAccessibleName("jButtonBack");
        jMonthYearLabel.getAccessibleContext().setAccessibleName("");
        //jMonthYearLabel.setFont(calendaryHands);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemMonthViewItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jMenuItemMonthViewItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            switchPanels(jMonthPanel);
            jMonthYearLabel.setText(monthLabel);
            panelSelected = 1;
        }
    }//GEN-LAST:event_jMenuItemMonthViewItemStateChanged

    private void jMenuItemYearViewItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jMenuItemYearViewItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            switchPanels(jYearPanel);
            jMonthYearLabel.setText(yearLabel);
            panelSelected = 0;
        }
    }//GEN-LAST:event_jMenuItemYearViewItemStateChanged

    private void jMenuItemWeekViewItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jMenuItemWeekViewItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            switchPanels(jWeekPanel);
            panelSelected = 2;
        }
    }//GEN-LAST:event_jMenuItemWeekViewItemStateChanged

    private void DateJumpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateJumpButtonActionPerformed
        switchPanelName();
        CalendarFiller.year = Integer.valueOf(jYearTextField.getText());
        CalendarFiller.month = Integer.valueOf(jMonthTextField.getText());
        CalendarFiller.date = Integer.valueOf(jDateText.getText());
        CalendarFiller.fillInTable(jMonthTable);
        CalendarFiller.fillInTable(jTableJan, jTableFeb, jTableMar, jTableApr, jTableMay, jTableJun, jTableJul, jTableAug, jTableSep, jTableOct, jTableNov, jTableDec);
    }//GEN-LAST:event_DateJumpButtonActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        if(panelSelected == 1){
            if(CalendarFiller.month < 12){
                CalendarFiller.month++;
            } else {
                CalendarFiller.month = 1;
                CalendarFiller.year++;
            }
        } else if(panelSelected == 2) {
            if(CalendarFiller.month == 12 && (CalendarFiller.date + 7 > 31)){
                CalendarFiller.month = 1;
                CalendarFiller.year++;
                CalendarFiller.date = CalendarFiller.date + 7 - 31;
            } else {
                cal.set(CalendarFiller.year, CalendarFiller.month - 1, CalendarFiller.date);
                int dayOfYear = cal.get(Calendar.DAY_OF_YEAR);
                dayOfYear += 7;
                Year y = Year.of(CalendarFiller.year) ;
                LocalDate ld = y.atDay(dayOfYear);
                CalendarFiller.month = ld.getMonthValue();
                CalendarFiller.date = ld.getDayOfMonth();
            }
        } else {
            CalendarFiller.year++;
        }
        jMonthTextField.setText(String.valueOf(CalendarFiller.month));
        jYearTextField.setText(String.valueOf(CalendarFiller.year));
        jDateText.setText(String.valueOf(CalendarFiller.date));
        switchPanelName();
        CalendarFiller.fillInTable(jMonthTable);
        CalendarFiller.fillInTable(jTableJan, jTableFeb, jTableMar, jTableApr, jTableMay, jTableJun, jTableJul, jTableAug, jTableSep, jTableOct, jTableNov, jTableDec);
    }//GEN-LAST:event_jButtonNextActionPerformed
    
    //DefaultTableModel mod;
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       CalendarFiller.addModel(jMonthTable);
       CalendarFiller.addModel(jWeekTable);
       CalendarFiller.addModel(jTableJan, jTableFeb, jTableMar, jTableApr, jTableMay, jTableJun, jTableJul, jTableAug, jTableSep, jTableOct, jTableNov, jTableDec);
    }//GEN-LAST:event_formWindowOpened

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        if(panelSelected == 1){
            if(CalendarFiller.month > 1){
                CalendarFiller.month--;
            } else {
                CalendarFiller.month = 12;
                CalendarFiller.year--;
            }
        } else if(panelSelected == 2) {
            if(CalendarFiller.month == 1 && (CalendarFiller.date - 7 < 0)){
                CalendarFiller.month = 12;
                CalendarFiller.year--;
                CalendarFiller.date = 31 + CalendarFiller.date - 7;
            } else {
                cal.set(CalendarFiller.year, CalendarFiller.month - 1, CalendarFiller.date);
                int dayOfYear = cal.get(Calendar.DAY_OF_YEAR);
                dayOfYear -= 7;
                Year y = Year.of(CalendarFiller.year) ;
                LocalDate ld = y.atDay(dayOfYear);
                CalendarFiller.month = ld.getMonthValue();
                CalendarFiller.date = ld.getDayOfMonth();
            }
        } else {
            CalendarFiller.year--;
        }
        jMonthTextField.setText(String.valueOf(CalendarFiller.month));
        jYearTextField.setText(String.valueOf(CalendarFiller.year));
        jDateText.setText(String.valueOf(CalendarFiller.date));
        switchPanelName();
        CalendarFiller.fillInTable(jMonthTable);
        CalendarFiller.fillInTable(jTableJan, jTableFeb, jTableMar, jTableApr, jTableMay, jTableJun, jTableJul, jTableAug, jTableSep, jTableOct, jTableNov, jTableDec);
    }//GEN-LAST:event_jButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalendarMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalendarMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalendarMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalendarMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalendarMain().setVisible(true);
            }
        });
    }
    
    public void switchPanels(JPanel panel){
        jLayeredPanel.removeAll();
        jLayeredPanel.add(panel);
        jLayeredPanel.repaint();
        jLayeredPanel.revalidate();
    }
    
    private void switchPanelName(){
        cal.set(MONTH, Integer.parseInt(jMonthTextField.getText()) - 1);
        monthLabel = cal.getDisplayName(MONTH, Calendar.LONG, Locale.ENGLISH);
        yearLabel = jYearTextField.getText();
        if(panelSelected == 0){
            jMonthYearLabel.setText(yearLabel);
        } else if(panelSelected == 1){
            jMonthYearLabel.setText(monthLabel);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DateJumpButton;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JTextField jDateText;
    private javax.swing.JList<String> jEventList;
    private javax.swing.JLayeredPane jLayeredPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem jMenuItemMonthView;
    private javax.swing.JRadioButtonMenuItem jMenuItemWeekView;
    private javax.swing.JRadioButtonMenuItem jMenuItemYearView;
    private javax.swing.JPanel jMonthPanel;
    private javax.swing.JTable jMonthTable;
    private javax.swing.JTextField jMonthTextField;
    private java.awt.Label jMonthYearLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTableApr;
    private javax.swing.JTable jTableAug;
    private javax.swing.JTable jTableDec;
    private javax.swing.JTable jTableFeb;
    private javax.swing.JTable jTableJan;
    private javax.swing.JTable jTableJul;
    private javax.swing.JTable jTableJun;
    private javax.swing.JTable jTableMar;
    private javax.swing.JTable jTableMay;
    private javax.swing.JTable jTableNov;
    private javax.swing.JTable jTableOct;
    private javax.swing.JTable jTableSep;
    private javax.swing.JPanel jWeekPanel;
    private javax.swing.JTable jWeekTable;
    private javax.swing.JPanel jYearPanel;
    private javax.swing.JTextField jYearTextField;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private javax.swing.ButtonGroup viewMenueGroup;
    // End of variables declaration//GEN-END:variables

}
